name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 1.8/8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean package -B

    - name: Rename JAR file
      run: |
        JAR_FILE=$(ls target/*.jar | head -n 1)
        cp "$JAR_FILE" "CompiledJava#${{ github.run_number }}.jar"

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: CompiledJava#${{ github.run_number }}
        path: CompiledJava#${{ github.run_number }}.jar
        
